<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>GroupFinity.Mascot</RootNamespace>
    <AssemblyName>Shimeji-ee</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Jint" Version="4.2.2" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\ogshimejieesrc\conf\**\*">
      <Link>conf\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
