#Shimeji-ee Configuration Options
#Mon Jul 08 21:48:50 WST 2013
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger
ActiveShimeji=Shimeji
DurationScale=0.5
Breeding=true
Transients=true
MaxClones=12
OllamaEnabled=true
OllamaUrl=http://127.0.0.1:11434
OllamaModel=
